# Manual push config; needs client.crt/client.key at the repo root.
#   BST_FLAGS="--config /src/buildstream-push.conf" just bst build <element>
artifacts:
  servers:
  - url: https://cache.projectbluefin.io:11002
    push: true
    connection-config:
      keepalive-time: 180
      retry-limit: 5
      retry-delay: 1000
      request-timeout: 180
    auth:
      client-key: /src/client.key
      client-cert: /src/client.crt
source-caches:
  servers:
  - url: https://cache.projectbluefin.io:11002
    push: true
    connection-config:
      keepalive-time: 180
      retry-limit: 5
      retry-delay: 1000
      request-timeout: 180
    auth:
      client-key: /src/client.key
      client-cert: /src/client.crt
