name: cosmic

min-version: 2.5

element-path: elements

(@):
  - include/aliases.yml

options:
  arch:
    type: arch
    description: Machine architecture
    variable: arch
    values:
      - aarch64
      - x86_64
      - riscv64

sandbox:
  build-arch: "%{arch}"

variables:
  (?):
    - arch == "x86_64":
        abi: "x86_64-linux-gnu"
    - arch == "aarch64":
        abi: "aarch64-linux-gnu"
    - arch == "riscv64":
        abi: "riscv64-linux-gnu"

elements:
  manual:
    # All Rust elements use kind:manual. If a Rust element ever uses kind:make
    # or kind:autotools, these env vars must be added there too.
    environment:
      RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
      PKG_CONFIG_PATH: "/usr/lib/pkgconfig:/usr/share/pkgconfig"
  meson:
    variables:
      meson-global: >-
        --buildtype=plain
        --wrap-mode=nodownload
  cmake:
    variables:
      cmake-global: >-
        -DCMAKE_BUILD_TYPE=RelWithDebInfo

plugins:
  - origin: junction
    junction: plugins/buildstream-plugins.bst
    elements:
      - autotools
      - meson
      - cmake
      - make
    sources:
      - patch

  - origin: local
    path: plugins/local/sources
    sources:
      - cargo2

  - origin: junction
    junction: plugins/buildstream-plugins-community.bst
    elements: []
    sources:
      - git_repo
      - patch_queue

sources:
  git_repo:
    config:
      ref-format: git-describe
  cargo2:
    config:
      vendor-dir: ".vendored"
      git-mirrors:
        https://github.com/pop-os/: "github:pop-os/"
        https://github.com/smithay/: "github:smithay/"
        https://github.com/Drakulix/: "github:Drakulix/"
        https://github.com/kennylevinsen/: "srht:~kennylevinsen/"
